name: Tests

on: pull_request

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Setup RSpec
        run: |
          [ -f Gemfile ] && bundle
          gem install --no-document rspec
      - name: RSpec Report
        run: rspec --force-color --format documentation --exclude-pattern "./spec/helpers/*"